name: Hexo Deploy

# 只监听 source 分支的改动
on:
  push:
    branches:
      - gh-pages

# 自定义环境变量
env:
  GIT_USER: LinYuXiang087241
  GIT_EMAIL: 1524204934@qq.com
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 获取博客源码和主题
      - name: Checkout
        uses: actions/checkout@v2

      # 这里用的是 Node.js 13.x，14.x 生成 Hexo 静态页面会有问题
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # 安装依赖
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      - name: Check out hexo
        run: |
          git config user.name "LinYuXiang087241"
          git config user.email "1524204934@qq.com"
          hexo version
          hexo clean
          hexo generate
          hexo d